-- Seed all countries worldwide for the PayKey system
-- This populates the countries table with all major countries globally

-- Clear existing countries data (optional - comment out if you want to keep existing data)
-- DELETE FROM countries;

-- Insert all countries worldwide with their ISO codes and currencies
-- Data includes 195+ countries recognized by the United Nations

INSERT INTO countries (code, name, currency, isActive) VALUES
-- Africa
('AF', 'Afghanistan', 'AFN', true),
('AL', 'Albania', 'ALL', true),
('DZ', 'Algeria', 'DZD', true),
('AO', 'Angola', 'AOA', true),
('AR', 'Argentina', 'ARS', true),
('AM', 'Armenia', 'AMD', true),
('AU', 'Australia', 'AUD', true),
('AT', 'Austria', 'EUR', true),
('AZ', 'Azerbaijan', 'AZN', true),
('BH', 'Bahrain', 'BHD', true),
('BD', 'Bangladesh', 'BDT', true),
('BY', 'Belarus', 'BYN', true),
('BE', 'Belgium', 'EUR', true),
('BZ', 'Belize', 'BZD', true),
('BJ', 'Benin', 'XOF', true),
('BT', 'Bhutan', 'BTN', true),
('BO', 'Bolivia', 'BOB', true),
('BA', 'Bosnia and Herzegovina', 'BAM', true),
('BW', 'Botswana', 'BWP', true),
('BR', 'Brazil', 'BRL', true),
('BN', 'Brunei', 'BND', true),
('BG', 'Bulgaria', 'BGN', true),
('BF', 'Burkina Faso', 'XOF', true),
('BI', 'Burundi', 'BIF', true),
('KH', 'Cambodia', 'KHR', true),
('CM', 'Cameroon', 'XAF', true),
('CA', 'Canada', 'CAD', true),
('CV', 'Cape Verde', 'CVE', true),
('CF', 'Central African Republic', 'XAF', true),
('TD', 'Chad', 'XAF', true),
('CL', 'Chile', 'CLP', true),
('CN', 'China', 'CNY', true),
('CO', 'Colombia', 'COP', true),
('KM', 'Comoros', 'KMF', true),
('CG', 'Congo', 'XAF', true),
('CD', 'Congo (Democratic Republic)', 'CDF', true),
('CR', 'Costa Rica', 'CRC', true),
('CI', 'Côte d''Ivoire', 'XOF', true),
('HR', 'Croatia', 'HRK', true),
('CU', 'Cuba', 'CUP', true),
('CY', 'Cyprus', 'EUR', true),
('CZ', 'Czech Republic', 'CZK', true),
('DK', 'Denmark', 'DKK', true),
('DJ', 'Djibouti', 'DJF', true),
('DM', 'Dominica', 'XCD', true),
('DO', 'Dominican Republic', 'DOP', true),
('EC', 'Ecuador', 'USD', true),
('EG', 'Egypt', 'EGP', true),
('SV', 'El Salvador', 'USD', true),
('GQ', 'Equatorial Guinea', 'XAF', true),
('ER', 'Eritrea', 'ERN', true),
('EE', 'Estonia', 'EUR', true),
('SZ', 'Eswatini', 'SZL', true),
('ET', 'Ethiopia', 'ETB', true),
('FJ', 'Fiji', 'FJD', true),
('FI', 'Finland', 'EUR', true),
('FR', 'France', 'EUR', true),
('GA', 'Gabon', 'XAF', true),
('GM', 'Gambia', 'GMD', true),
('GE', 'Georgia', 'GEL', true),
('DE', 'Germany', 'EUR', true),
('GH', 'Ghana', 'GHS', true),
('GR', 'Greece', 'EUR', true),
('GD', 'Grenada', 'XCD', true),
('GT', 'Guatemala', 'GTQ', true),
('GN', 'Guinea', 'GNF', true),
('GW', 'Guinea-Bissau', 'XOF', true),
('GY', 'Guyana', 'GYD', true),
('HT', 'Haiti', 'HTG', true),
('HN', 'Honduras', 'HNL', true),
('HU', 'Hungary', 'HUF', true),
('IS', 'Iceland', 'ISK', true),
('IN', 'India', 'INR', true),
('ID', 'Indonesia', 'IDR', true),
('IR', 'Iran', 'IRR', true),
('IQ', 'Iraq', 'IQD', true),
('IE', 'Ireland', 'EUR', true),
('IL', 'Israel', 'ILS', true),
('IT', 'Italy', 'EUR', true),
('JM', 'Jamaica', 'JMD', true),
('JP', 'Japan', 'JPY', true),
('JO', 'Jordan', 'JOD', true),
('KZ', 'Kazakhstan', 'KZT', true),
('KE', 'Kenya', 'KES', true),
('KI', 'Kiribati', 'AUD', true),
('KP', 'Korea (North)', 'KPW', true),
('KR', 'Korea (South)', 'KRW', true),
('KW', 'Kuwait', 'KWD', true),
('KG', 'Kyrgyzstan', 'KGS', true),
('LA', 'Laos', 'LAK', true),
('LV', 'Latvia', 'EUR', true),
('LB', 'Lebanon', 'LBP', true),
('LS', 'Lesotho', 'LSL', true),
('LR', 'Liberia', 'LRD', true),
('LY', 'Libya', 'LYD', true),
('LI', 'Liechtenstein', 'CHF', true),
('LT', 'Lithuania', 'EUR', true),
('LU', 'Luxembourg', 'EUR', true),
('MG', 'Madagascar', 'MGA', true),
('MW', 'Malawi', 'MWK', true),
('MY', 'Malaysia', 'MYR', true),
('MV', 'Maldives', 'MVR', true),
('ML', 'Mali', 'XOF', true),
('MT', 'Malta', 'EUR', true),
('MH', 'Marshall Islands', 'USD', true),
('MR', 'Mauritania', 'MRU', true),
('MU', 'Mauritius', 'MUR', true),
('MX', 'Mexico', 'MXN', true),
('FM', 'Micronesia', 'USD', true),
('MD', 'Moldova', 'MDL', true),
('MC', 'Monaco', 'EUR', true),
('MN', 'Mongolia', 'MNT', true),
('ME', 'Montenegro', 'EUR', true),
('MA', 'Morocco', 'MAD', true),
('MZ', 'Mozambique', 'MZN', true),
('MM', 'Myanmar', 'MMK', true),
('NA', 'Namibia', 'NAD', true),
('NR', 'Nauru', 'AUD', true),
('NP', 'Nepal', 'NPR', true),
('NL', 'Netherlands', 'EUR', true),
('NZ', 'New Zealand', 'NZD', true),
('NI', 'Nicaragua', 'NIO', true),
('NE', 'Niger', 'XOF', true),
('NG', 'Nigeria', 'NGN', true),
('MK', 'North Macedonia', 'MKD', true),
('NO', 'Norway', 'NOK', true),
('OM', 'Oman', 'OMR', true),
('PK', 'Pakistan', 'PKR', true),
('PW', 'Palau', 'USD', true),
('PS', 'Palestine', 'ILS', true),
('PA', 'Panama', 'PAB', true),
('PG', 'Papua New Guinea', 'PGK', true),
('PY', 'Paraguay', 'PYG', true),
('PE', 'Peru', 'PEN', true),
('PH', 'Philippines', 'PHP', true),
('PL', 'Poland', 'PLN', true),
('PT', 'Portugal', 'EUR', true),
('QA', 'Qatar', 'QAR', true),
('RO', 'Romania', 'RON', true),
('RU', 'Russia', 'RUB', true),
('RW', 'Rwanda', 'RWF', true),
('KN', 'Saint Kitts and Nevis', 'XCD', true),
('LC', 'Saint Lucia', 'XCD', true),
('VC', 'Saint Vincent and the Grenadines', 'XCD', true),
('WS', 'Samoa', 'WST', true),
('SM', 'San Marino', 'EUR', true),
('ST', 'São Tomé and Príncipe', 'STN', true),
('SA', 'Saudi Arabia', 'SAR', true),
('SN', 'Senegal', 'XOF', true),
('RS', 'Serbia', 'RSD', true),
('SC', 'Seychelles', 'SCR', true),
('SL', 'Sierra Leone', 'SLL', true),
('SG', 'Singapore', 'SGD', true),
('SK', 'Slovakia', 'EUR', true),
('SI', 'Slovenia', 'EUR', true),
('SB', 'Solomon Islands', 'SBD', true),
('SO', 'Somalia', 'SOS', true),
('ZA', 'South Africa', 'ZAR', true),
('SS', 'South Sudan', 'SSP', true),
('ES', 'Spain', 'EUR', true),
('LK', 'Sri Lanka', 'LKR', true),
('SD', 'Sudan', 'SDG', true),
('SR', 'Suriname', 'SRD', true),
('SE', 'Sweden', 'SEK', true),
('CH', 'Switzerland', 'CHF', true),
('SY', 'Syria', 'SYP', true),
('TW', 'Taiwan', 'TWD', true),
('TJ', 'Tajikistan', 'TJS', true),
('TZ', 'Tanzania', 'TZS', true),
('TH', 'Thailand', 'THB', true),
('TL', 'Timor-Leste', 'USD', true),
('TG', 'Togo', 'XOF', true),
('TO', 'Tonga', 'TOP', true),
('TT', 'Trinidad and Tobago', 'TTD', true),
('TN', 'Tunisia', 'TND', true),
('TR', 'Turkey', 'TRY', true),
('TM', 'Turkmenistan', 'TMT', true),
('TV', 'Tuvalu', 'AUD', true),
('UG', 'Uganda', 'UGX', true),
('UA', 'Ukraine', 'UAH', true),
('AE', 'United Arab Emirates', 'AED', true),
('GB', 'United Kingdom', 'GBP', true),
('US', 'United States', 'USD', true),
('UY', 'Uruguay', 'UYU', true),
('UZ', 'Uzbekistan', 'UZS', true),
('VU', 'Vanuatu', 'VUV', true),
('VA', 'Vatican City', 'EUR', true),
('VE', 'Venezuela', 'VES', true),
('VN', 'Vietnam', 'VND', true),
('YE', 'Yemen', 'YER', true),
('ZM', 'Zambia', 'ZMW', true),
('ZW', 'Zimbabwe', 'ZWL', true),

-- Additional territories and dependencies
('AD', 'Andorra', 'EUR', true),
('AI', 'Anguilla', 'XCD', true),
('AG', 'Antigua and Barbuda', 'XCD', true),
('AW', 'Aruba', 'AWG', true),
('BS', 'Bahamas', 'BSD', true),
('BB', 'Barbados', 'BBD', true),
('BV', 'Bouvet Island', 'NOK', true),
('IO', 'British Indian Ocean Territory', 'USD', true),
('VG', 'British Virgin Islands', 'USD', true),
('KY', 'Cayman Islands', 'KYD', true),
('CX', 'Christmas Island', 'AUD', true),
('CC', 'Cocos (Keeling) Islands', 'AUD', true),
('CK', 'Cook Islands', 'NZD', true),
('CW', 'Curaçao', 'ANG', true),
('FK', 'Falkland Islands', 'FKP', true),
('FO', 'Faroe Islands', 'DKK', true),
('GF', 'French Guiana', 'EUR', true),
('PF', 'French Polynesia', 'XPF', true),
('TF', 'French Southern Territories', 'EUR', true),
('GI', 'Gibraltar', 'GIP', true),
('GL', 'Greenland', 'DKK', true),
('GP', 'Guadeloupe', 'EUR', true),
('GU', 'Guam', 'USD', true),
('GG', 'Guernsey', 'GBP', true),
('HM', 'Heard Island and McDonald Islands', 'AUD', true),
('HK', 'Hong Kong', 'HKD', true),
('IM', 'Isle of Man', 'GBP', true),
('JE', 'Jersey', 'GBP', true),
('MQ', 'Martinique', 'EUR', true),
('YT', 'Mayotte', 'EUR', true),
('MS', 'Montserrat', 'XCD', true),
('NC', 'New Caledonia', 'XPF', true),
('NF', 'Norfolk Island', 'AUD', true),
('MP', 'Northern Mariana Islands', 'USD', true),
('NU', 'Niue', 'NZD', true),
('NF', 'Norfolk Island', 'AUD', true),
('NR', 'Nauru', 'AUD', true),
('NP', 'Nepal', 'NPR', true),
('AN', 'Netherlands Antilles', 'ANG', true),
('NU', 'Niue', 'NZD', true),
('NF', 'Norfolk Island', 'AUD', true),
('MP', 'Northern Mariana Islands', 'USD', true),
('UM', 'United States Minor Outlying Islands', 'USD', true),
('VI', 'United States Virgin Islands', 'USD', true),
('WF', 'Wallis and Futuna', 'XPF', true)

ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    currency = EXCLUDED.currency,
    isActive = EXCLUDED.isActive;

-- Display summary
SELECT 
    COUNT(*) as total_countries,
    COUNT(CASE WHEN isActive = true THEN 1 END) as active_countries,
    COUNT(DISTINCT currency) as unique_currencies
FROM countries;