import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1764190251230 implements MigrationInterface {
    name = 'InitialSchema1764190251230'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "properties" DROP CONSTRAINT "properties_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "workers" DROP CONSTRAINT "workers_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "workers" DROP CONSTRAINT "workers_propertyId_fkey"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP CONSTRAINT "pay_periods_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" DROP CONSTRAINT "tax_submissions_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" DROP CONSTRAINT "tax_submissions_payPeriodId_fkey"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP CONSTRAINT "payroll_records_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP CONSTRAINT "payroll_records_workerId_fkey"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "transactions_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "transactions_workerId_fkey"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "transactions_propertyId_fkey"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "transactions_payPeriodId_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workers_userid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workers_propertyid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pay_periods_userid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tax_submissions_userid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tax_submissions_payperiodid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payroll_records_userid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payroll_records_workerid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payroll_records_period"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transactions_userid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transactions_workerid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transactions_payperiodid"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_requests_leavetype_enum" AS ENUM('ANNUAL', 'SICK', 'MATERNITY', 'PATERNITY', 'EMERGENCY', 'UNPAID')`);
        await queryRunner.query(`CREATE TYPE "public"."leave_requests_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "leave_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workerId" uuid NOT NULL, "requestedById" uuid NOT NULL, "leaveType" "public"."leave_requests_leavetype_enum" NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "totalDays" integer NOT NULL, "reason" text, "status" "public"."leave_requests_status_enum" NOT NULL DEFAULT 'PENDING', "approvedById" uuid, "approvedAt" TIMESTAMP, "rejectionReason" text, "dailyPayRate" numeric(10,2), "paidLeave" boolean NOT NULL DEFAULT false, "emergencyContact" text, "emergencyPhone" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d3abcf9a16cef1450129e06fa9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."terminations_reason_enum" AS ENUM('RESIGNATION', 'DISMISSAL', 'CONTRACT_END', 'ILLNESS', 'DEATH', 'RETIREMENT', 'REDUNDANCY', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "terminations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workerId" uuid NOT NULL, "userId" uuid NOT NULL, "reason" "public"."terminations_reason_enum" NOT NULL, "terminationDate" date NOT NULL, "lastWorkingDate" date, "noticePeriodDays" integer NOT NULL DEFAULT '0', "notes" text, "proratedSalary" numeric(10,2) NOT NULL, "unusedLeavePayout" numeric(10,2) NOT NULL, "severancePay" numeric(10,2) NOT NULL DEFAULT '0', "totalFinalPayment" numeric(10,2) NOT NULL, "paymentBreakdown" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fbcd33fb27fe64566fa4f9281d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."time_entries_status_enum" AS ENUM('IN_PROGRESS', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "time_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workerId" character varying NOT NULL, "userId" uuid NOT NULL, "propertyId" character varying, "clockInTime" TIMESTAMP NOT NULL, "clockOutTime" TIMESTAMP, "clockInLatitude" numeric(10,6), "clockInLongitude" numeric(10,6), "clockOutLatitude" numeric(10,6), "clockOutLongitude" numeric(10,6), "totalHours" numeric(5,2), "status" "public"."time_entries_status_enum" NOT NULL DEFAULT 'IN_PROGRESS', "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b8bc5f10269ba2fe88708904aa0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_tier_enum" AS ENUM('FREE', 'BASIC', 'GOLD', 'PLATINUM')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('ACTIVE', 'CANCELLED', 'EXPIRED', 'PAST_DUE', 'TRIAL')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tier" "public"."subscriptions_tier_enum" NOT NULL DEFAULT 'FREE', "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'ACTIVE', "amount" numeric(10,2), "currency" character varying NOT NULL DEFAULT 'USD', "startDate" TIMESTAMP WITH TIME ZONE, "endDate" TIMESTAMP WITH TIME ZONE, "nextBillingDate" TIMESTAMP WITH TIME ZONE, "stripeSubscriptionId" character varying, "stripePriceId" character varying, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tax_configs_taxtype_enum" AS ENUM('PAYE', 'SHIF', 'NSSF_TIER1', 'NSSF_TIER2', 'HOUSING_LEVY')`);
        await queryRunner.query(`CREATE TYPE "public"."tax_configs_ratetype_enum" AS ENUM('PERCENTAGE', 'GRADUATED', 'TIERED')`);
        await queryRunner.query(`CREATE TABLE "tax_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "taxType" "public"."tax_configs_taxtype_enum" NOT NULL, "rateType" "public"."tax_configs_ratetype_enum" NOT NULL, "effectiveFrom" date NOT NULL, "effectiveTo" date, "configuration" jsonb NOT NULL, "paymentDeadline" character varying NOT NULL DEFAULT '9th of following month', "isActive" boolean NOT NULL DEFAULT true, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fefada95a3b9edeac02a5c7b5dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_payments_status_enum" AS ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "subscription_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscriptionId" uuid NOT NULL, "userId" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "status" "public"."subscription_payments_status_enum" NOT NULL DEFAULT 'COMPLETED', "paymentMethod" character varying NOT NULL, "billingPeriod" character varying NOT NULL, "periodStart" TIMESTAMP WITH TIME ZONE NOT NULL, "periodEnd" TIMESTAMP WITH TIME ZONE NOT NULL, "dueDate" TIMESTAMP WITH TIME ZONE NOT NULL, "paidDate" TIMESTAMP WITH TIME ZONE, "invoiceNumber" character varying, "paymentProvider" character varying, "transactionId" character varying, "metadata" jsonb, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1b7a76365fd477de59cba0ab957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tax_payments_taxtype_enum" AS ENUM('PAYE', 'SHIF', 'NSSF_TIER1', 'NSSF_TIER2', 'HOUSING_LEVY')`);
        await queryRunner.query(`CREATE TYPE "public"."tax_payments_paymentmethod_enum" AS ENUM('MPESA', 'BANK')`);
        await queryRunner.query(`CREATE TYPE "public"."tax_payments_status_enum" AS ENUM('PENDING', 'PAID', 'OVERDUE')`);
        await queryRunner.query(`CREATE TABLE "tax_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "taxType" "public"."tax_payments_taxtype_enum" NOT NULL, "paymentYear" integer NOT NULL, "paymentMonth" integer NOT NULL, "amount" numeric(12,2) NOT NULL, "paymentDate" date, "paymentMethod" "public"."tax_payments_paymentmethod_enum", "receiptNumber" character varying, "status" "public"."tax_payments_status_enum" NOT NULL DEFAULT 'PENDING', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_300678915f007d7c94439ac5dd3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."exports_exporttype_enum" AS ENUM('QUICKBOOKS_IIF', 'XERO_CSV', 'GENERIC_CSV', 'EXCEL')`);
        await queryRunner.query(`CREATE TABLE "exports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "exportType" "public"."exports_exporttype_enum" NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "fileName" character varying NOT NULL, "filePath" character varying, "recordCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bcf8528d214cbfc68c01f337511" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."accounting_exports_format_enum" AS ENUM('CSV', 'EXCEL', 'QUICKBOOKS', 'XERO', 'SAGE')`);
        await queryRunner.query(`CREATE TYPE "public"."accounting_exports_status_enum" AS ENUM('PENDING', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "accounting_exports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "payPeriodId" uuid NOT NULL, "format" "public"."accounting_exports_format_enum" NOT NULL, "status" "public"."accounting_exports_status_enum" NOT NULL DEFAULT 'PENDING', "filePath" character varying, "externalId" character varying, "errorMessage" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_80eddc407420d146a07f03836de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."account_mappings_category_enum" AS ENUM('SALARY_EXPENSE', 'PAYE_LIABILITY', 'NSSF_LIABILITY', 'NHIF_LIABILITY', 'HOUSING_LEVY_LIABILITY', 'CASH_BANK')`);
        await queryRunner.query(`CREATE TABLE "account_mappings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "category" "public"."account_mappings_category_enum" NOT NULL, "accountCode" character varying NOT NULL, "accountName" character varying NOT NULL, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_564623d7f786d686e3b834f047a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isResident"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "countryOfOrigin"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isOnboardingCompleted"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "idType"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "nationalityId"`);
        await queryRunner.query(`CREATE TYPE "public"."users_idtype_enum" AS ENUM('NATIONAL_ID', 'ALIEN_ID', 'PASSPORT')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "idtype" "public"."users_idtype_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "nationalityid" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isonboardingcompleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "payPeriodId" character varying`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "bonuses" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "otherEarnings" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "otherDeductions" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`CREATE TYPE "public"."payroll_records_status_enum" AS ENUM('draft', 'finalized', 'paid')`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "status" "public"."payroll_records_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "finalizedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tax_tables" ALTER COLUMN "isActive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_tables" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "tax_tables" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tax_tables" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "tax_tables" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('ADMIN', 'USER')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL DEFAULT 'USER'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "tier"`);
        await queryRunner.query(`CREATE TYPE "public"."users_tier_enum" AS ENUM('FREE', 'BASIC', 'GOLD', 'PLATINUM')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "tier" "public"."users_tier_enum" NOT NULL DEFAULT 'FREE'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "countryId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "countryId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "properties" ALTER COLUMN "geofenceRadius" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "properties" ALTER COLUMN "isActive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "employmentType"`);
        await queryRunner.query(`CREATE TYPE "public"."workers_employmenttype_enum" AS ENUM('FIXED', 'HOURLY')`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "employmentType" "public"."workers_employmenttype_enum" NOT NULL DEFAULT 'FIXED'`);
        await queryRunner.query(`ALTER TABLE "workers" ALTER COLUMN "isActive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workers" ALTER COLUMN "leaveBalance" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workers" ALTER COLUMN "housingAllowance" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workers" ALTER COLUMN "transportAllowance" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "paymentFrequency"`);
        await queryRunner.query(`CREATE TYPE "public"."workers_paymentfrequency_enum" AS ENUM('MONTHLY', 'WEEKLY')`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "paymentFrequency" "public"."workers_paymentfrequency_enum" NOT NULL DEFAULT 'MONTHLY'`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`CREATE TYPE "public"."workers_paymentmethod_enum" AS ENUM('MPESA', 'BANK', 'CASH')`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "paymentMethod" "public"."workers_paymentmethod_enum" NOT NULL DEFAULT 'MPESA'`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "terminationId"`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "terminationId" character varying`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "terminatedAt"`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "terminatedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "frequency"`);
        await queryRunner.query(`CREATE TYPE "public"."pay_periods_frequency_enum" AS ENUM('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY')`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "frequency" "public"."pay_periods_frequency_enum" NOT NULL DEFAULT 'MONTHLY'`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."pay_periods_status_enum" AS ENUM('DRAFT', 'ACTIVE', 'PROCESSING', 'COMPLETED', 'CLOSED')`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "status" "public"."pay_periods_status_enum" NOT NULL DEFAULT 'DRAFT'`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ALTER COLUMN "totalGrossAmount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ALTER COLUMN "totalNetAmount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ALTER COLUMN "totalTaxAmount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ALTER COLUMN "totalWorkers" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ALTER COLUMN "processedWorkers" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "notes" json`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "createdBy" character varying`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "approvedBy"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "approvedBy" character varying`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "approvedAt"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "approvedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "processedAt"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "processedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ALTER COLUMN "totalPaye" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ALTER COLUMN "totalNssf" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ALTER COLUMN "totalNhif" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ALTER COLUMN "totalHousingLevy" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."tax_submissions_status_enum" AS ENUM('PENDING', 'FILED')`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ADD "status" "public"."tax_submissions_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" DROP COLUMN "filingDate"`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ADD "filingDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ALTER COLUMN "paymentStatus" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ALTER COLUMN "paymentMethod" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "paymentDate"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "paymentDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "taxBreakdown"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "taxBreakdown" json`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "deductions"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "deductions" json`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "currency" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_type_enum" AS ENUM('SUBSCRIPTION', 'SALARY_PAYOUT', 'TOPUP')`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "type" "public"."transactions_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED')`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "status" "public"."transactions_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "propertyId"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "propertyId" character varying`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "countries" ALTER COLUMN "isActive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "countries" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "countries" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "countries" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "countries" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "properties" ADD CONSTRAINT "FK_6b55a80fd17a5bb77b753635496" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workers" ADD CONSTRAINT "FK_fdefd9252e90173f66271f76b96" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workers" ADD CONSTRAINT "FK_a3c397f93094ff3a2dcabda1623" FOREIGN KEY ("propertyId") REFERENCES "properties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_0f7d0f1eb654a646297210f50a0" FOREIGN KEY ("workerId") REFERENCES "workers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_68ac94e305b4002c3e7b5caaad2" FOREIGN KEY ("requestedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_7db9acba337a488517af94b4998" FOREIGN KEY ("approvedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ADD CONSTRAINT "FK_acb786d7df37dc0799ac4080ed6" FOREIGN KEY ("payPeriodId") REFERENCES "pay_periods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terminations" ADD CONSTRAINT "FK_08be6c625c457e30ad99c9d3c10" FOREIGN KEY ("workerId") REFERENCES "workers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terminations" ADD CONSTRAINT "FK_33887f52f0a31dae2b8dc1642cf" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_d1b452d7f0d45863303b7d30000" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD CONSTRAINT "FK_501b428f343aae23932440e18d8" FOREIGN KEY ("workerId") REFERENCES "workers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_payments" ADD CONSTRAINT "FK_b71c34361d0308a49ceed66d63b" FOREIGN KEY ("subscriptionId") REFERENCES "subscriptions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_payments" ADD CONSTRAINT "FK_3d23ead99f99e90de0a6bcd8bb1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exports" ADD CONSTRAINT "FK_cd97426e551b0cad4717f52b10d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_61ef4303498bf8d96be750751fd" FOREIGN KEY ("workerId") REFERENCES "workers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_2fcd161ed4709ffc46cd4e06b4a" FOREIGN KEY ("payPeriodId") REFERENCES "pay_periods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounting_exports" ADD CONSTRAINT "FK_db0ecfad3898d8fb6af1b215415" FOREIGN KEY ("payPeriodId") REFERENCES "pay_periods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "accounting_exports" DROP CONSTRAINT "FK_db0ecfad3898d8fb6af1b215415"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_2fcd161ed4709ffc46cd4e06b4a"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_61ef4303498bf8d96be750751fd"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41"`);
        await queryRunner.query(`ALTER TABLE "exports" DROP CONSTRAINT "FK_cd97426e551b0cad4717f52b10d"`);
        await queryRunner.query(`ALTER TABLE "tax_payments" DROP CONSTRAINT "FK_3d23ead99f99e90de0a6bcd8bb1"`);
        await queryRunner.query(`ALTER TABLE "subscription_payments" DROP CONSTRAINT "FK_b71c34361d0308a49ceed66d63b"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP CONSTRAINT "FK_501b428f343aae23932440e18d8"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_d1b452d7f0d45863303b7d30000"`);
        await queryRunner.query(`ALTER TABLE "terminations" DROP CONSTRAINT "FK_33887f52f0a31dae2b8dc1642cf"`);
        await queryRunner.query(`ALTER TABLE "terminations" DROP CONSTRAINT "FK_08be6c625c457e30ad99c9d3c10"`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" DROP CONSTRAINT "FK_acb786d7df37dc0799ac4080ed6"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_7db9acba337a488517af94b4998"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_68ac94e305b4002c3e7b5caaad2"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_0f7d0f1eb654a646297210f50a0"`);
        await queryRunner.query(`ALTER TABLE "workers" DROP CONSTRAINT "FK_a3c397f93094ff3a2dcabda1623"`);
        await queryRunner.query(`ALTER TABLE "workers" DROP CONSTRAINT "FK_fdefd9252e90173f66271f76b96"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP CONSTRAINT "FK_6b55a80fd17a5bb77b753635496"`);
        await queryRunner.query(`ALTER TABLE "countries" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "countries" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "countries" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "countries" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "countries" ALTER COLUMN "isActive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "propertyId"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "propertyId" uuid`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "status" character varying DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_type_enum"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "currency" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "deductions"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "deductions" jsonb`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "taxBreakdown"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "taxBreakdown" jsonb`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "paymentDate"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "paymentDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ALTER COLUMN "paymentMethod" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ALTER COLUMN "paymentStatus" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" DROP COLUMN "filingDate"`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ADD "filingDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."tax_submissions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ADD "status" character varying DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ALTER COLUMN "totalHousingLevy" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ALTER COLUMN "totalNhif" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ALTER COLUMN "totalNssf" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ALTER COLUMN "totalPaye" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "processedAt"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "processedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "approvedAt"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "approvedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "approvedBy"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "approvedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "createdBy" uuid`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "notes" jsonb`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ALTER COLUMN "processedWorkers" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ALTER COLUMN "totalWorkers" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ALTER COLUMN "totalTaxAmount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ALTER COLUMN "totalNetAmount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ALTER COLUMN "totalGrossAmount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."pay_periods_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "status" character varying DEFAULT 'DRAFT'`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "frequency"`);
        await queryRunner.query(`DROP TYPE "public"."pay_periods_frequency_enum"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "frequency" character varying DEFAULT 'MONTHLY'`);
        await queryRunner.query(`ALTER TABLE "pay_periods" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "terminatedAt"`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "terminatedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "terminationId"`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "terminationId" uuid`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`DROP TYPE "public"."workers_paymentmethod_enum"`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "paymentMethod" character varying DEFAULT 'MPESA'`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "paymentFrequency"`);
        await queryRunner.query(`DROP TYPE "public"."workers_paymentfrequency_enum"`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "paymentFrequency" character varying DEFAULT 'MONTHLY'`);
        await queryRunner.query(`ALTER TABLE "workers" ALTER COLUMN "transportAllowance" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workers" ALTER COLUMN "housingAllowance" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workers" ALTER COLUMN "leaveBalance" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workers" ALTER COLUMN "isActive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "employmentType"`);
        await queryRunner.query(`DROP TYPE "public"."workers_employmenttype_enum"`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "employmentType" character varying DEFAULT 'FIXED'`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "properties" ALTER COLUMN "isActive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "properties" ALTER COLUMN "geofenceRadius" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "countryId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "countryId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "tier"`);
        await queryRunner.query(`DROP TYPE "public"."users_tier_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "tier" character varying DEFAULT 'FREE'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying NOT NULL DEFAULT 'USER'`);
        await queryRunner.query(`ALTER TABLE "tax_tables" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "tax_tables" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tax_tables" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "tax_tables" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tax_tables" ALTER COLUMN "isActive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "finalizedAt"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."payroll_records_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "otherDeductions"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "otherEarnings"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "bonuses"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP COLUMN "payPeriodId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isonboardingcompleted"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "nationalityid"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "idtype"`);
        await queryRunner.query(`DROP TYPE "public"."users_idtype_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "nationalityId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "idType" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isOnboardingCompleted" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "countryOfOrigin" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isResident" boolean DEFAULT true`);
        await queryRunner.query(`DROP TABLE "account_mappings"`);
        await queryRunner.query(`DROP TYPE "public"."account_mappings_category_enum"`);
        await queryRunner.query(`DROP TABLE "accounting_exports"`);
        await queryRunner.query(`DROP TYPE "public"."accounting_exports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."accounting_exports_format_enum"`);
        await queryRunner.query(`DROP TABLE "exports"`);
        await queryRunner.query(`DROP TYPE "public"."exports_exporttype_enum"`);
        await queryRunner.query(`DROP TABLE "tax_payments"`);
        await queryRunner.query(`DROP TYPE "public"."tax_payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tax_payments_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tax_payments_taxtype_enum"`);
        await queryRunner.query(`DROP TABLE "subscription_payments"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_payments_status_enum"`);
        await queryRunner.query(`DROP TABLE "tax_configs"`);
        await queryRunner.query(`DROP TYPE "public"."tax_configs_ratetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tax_configs_taxtype_enum"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_tier_enum"`);
        await queryRunner.query(`DROP TABLE "time_entries"`);
        await queryRunner.query(`DROP TYPE "public"."time_entries_status_enum"`);
        await queryRunner.query(`DROP TABLE "terminations"`);
        await queryRunner.query(`DROP TYPE "public"."terminations_reason_enum"`);
        await queryRunner.query(`DROP TABLE "leave_requests"`);
        await queryRunner.query(`DROP TYPE "public"."leave_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leave_requests_leavetype_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_transactions_payperiodid" ON "transactions" ("payPeriodId") `);
        await queryRunner.query(`CREATE INDEX "idx_transactions_workerid" ON "transactions" ("workerId") `);
        await queryRunner.query(`CREATE INDEX "idx_transactions_userid" ON "transactions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_payroll_records_period" ON "payroll_records" ("periodStart", "periodEnd") `);
        await queryRunner.query(`CREATE INDEX "idx_payroll_records_workerid" ON "payroll_records" ("workerId") `);
        await queryRunner.query(`CREATE INDEX "idx_payroll_records_userid" ON "payroll_records" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_tax_submissions_payperiodid" ON "tax_submissions" ("payPeriodId") `);
        await queryRunner.query(`CREATE INDEX "idx_tax_submissions_userid" ON "tax_submissions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_pay_periods_userid" ON "pay_periods" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_workers_propertyid" ON "workers" ("propertyId") `);
        await queryRunner.query(`CREATE INDEX "idx_workers_userid" ON "workers" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "transactions_payPeriodId_fkey" FOREIGN KEY ("payPeriodId") REFERENCES "pay_periods"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "transactions_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "properties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "transactions_workerId_fkey" FOREIGN KEY ("workerId") REFERENCES "workers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "transactions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD CONSTRAINT "payroll_records_workerId_fkey" FOREIGN KEY ("workerId") REFERENCES "workers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD CONSTRAINT "payroll_records_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ADD CONSTRAINT "tax_submissions_payPeriodId_fkey" FOREIGN KEY ("payPeriodId") REFERENCES "pay_periods"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_submissions" ADD CONSTRAINT "tax_submissions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_periods" ADD CONSTRAINT "pay_periods_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workers" ADD CONSTRAINT "workers_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "properties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workers" ADD CONSTRAINT "workers_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "properties" ADD CONSTRAINT "properties_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
