// Mocks generated by Mockito 5.4.6 from annotations
// in mobile/test/features/payroll/payroll_workflow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mobile/features/payroll/data/models/pay_period_model.dart'
    as _i2;
import 'package:mobile/features/payroll/data/models/payroll_model.dart' as _i4;
import 'package:mobile/features/payroll/data/repositories/pay_period_repository.dart'
    as _i3;
import 'package:mobile/features/payroll/data/repositories/payroll_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePayPeriod_0 extends _i1.SmartFake implements _i2.PayPeriod {
  _FakePayPeriod_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayPeriodStatistics_1 extends _i1.SmartFake
    implements _i3.PayPeriodStatistics {
  _FakePayPeriodStatistics_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayrollProcessResponse_2 extends _i1.SmartFake
    implements _i4.PayrollProcessResponse {
  _FakePayrollProcessResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFundVerificationResult_3 extends _i1.SmartFake
    implements _i4.FundVerificationResult {
  _FakeFundVerificationResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJobStatusResult_4 extends _i1.SmartFake
    implements _i4.JobStatusResult {
  _FakeJobStatusResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayrollCalculation_5 extends _i1.SmartFake
    implements _i4.PayrollCalculation {
  _FakePayrollCalculation_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayslipPreview_6 extends _i1.SmartFake
    implements _i4.PayslipPreview {
  _FakePayslipPreview_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayrollSummary_7 extends _i1.SmartFake
    implements _i4.PayrollSummary {
  _FakePayrollSummary_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PayPeriodRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPayPeriodRepository extends _i1.Mock
    implements _i3.PayPeriodRepository {
  MockPayPeriodRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.PayPeriod>> getPayPeriods() =>
      (super.noSuchMethod(
            Invocation.method(#getPayPeriods, []),
            returnValue: _i5.Future<List<_i2.PayPeriod>>.value(
              <_i2.PayPeriod>[],
            ),
          )
          as _i5.Future<List<_i2.PayPeriod>>);

  @override
  _i5.Future<List<_i2.PayPeriod>> getPayPeriodsByStatus(
    _i2.PayPeriodStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPayPeriodsByStatus, [status]),
            returnValue: _i5.Future<List<_i2.PayPeriod>>.value(
              <_i2.PayPeriod>[],
            ),
          )
          as _i5.Future<List<_i2.PayPeriod>>);

  @override
  _i5.Future<_i2.PayPeriod> getPayPeriod(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#getPayPeriod, [payPeriodId]),
            returnValue: _i5.Future<_i2.PayPeriod>.value(
              _FakePayPeriod_0(
                this,
                Invocation.method(#getPayPeriod, [payPeriodId]),
              ),
            ),
          )
          as _i5.Future<_i2.PayPeriod>);

  @override
  _i5.Future<_i2.PayPeriod> getPayPeriodById(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#getPayPeriodById, [payPeriodId]),
            returnValue: _i5.Future<_i2.PayPeriod>.value(
              _FakePayPeriod_0(
                this,
                Invocation.method(#getPayPeriodById, [payPeriodId]),
              ),
            ),
          )
          as _i5.Future<_i2.PayPeriod>);

  @override
  _i5.Future<List<_i2.PayPeriod>> getCurrentPayPeriods() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPayPeriods, []),
            returnValue: _i5.Future<List<_i2.PayPeriod>>.value(
              <_i2.PayPeriod>[],
            ),
          )
          as _i5.Future<List<_i2.PayPeriod>>);

  @override
  _i5.Future<List<_i2.PayPeriod>> getCurrentPayPeriod() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPayPeriod, []),
            returnValue: _i5.Future<List<_i2.PayPeriod>>.value(
              <_i2.PayPeriod>[],
            ),
          )
          as _i5.Future<List<_i2.PayPeriod>>);

  @override
  _i5.Future<_i3.PayPeriodStatistics> getPayPeriodStatistics(
    String? payPeriodId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPayPeriodStatistics, [payPeriodId]),
            returnValue: _i5.Future<_i3.PayPeriodStatistics>.value(
              _FakePayPeriodStatistics_1(
                this,
                Invocation.method(#getPayPeriodStatistics, [payPeriodId]),
              ),
            ),
          )
          as _i5.Future<_i3.PayPeriodStatistics>);

  @override
  _i5.Future<_i2.PayPeriod> createPayPeriod(
    _i2.CreatePayPeriodRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPayPeriod, [request]),
            returnValue: _i5.Future<_i2.PayPeriod>.value(
              _FakePayPeriod_0(
                this,
                Invocation.method(#createPayPeriod, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.PayPeriod>);

  @override
  _i5.Future<_i2.PayPeriod> updatePayPeriod(
    String? payPeriodId,
    _i2.UpdatePayPeriodRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePayPeriod, [payPeriodId, request]),
            returnValue: _i5.Future<_i2.PayPeriod>.value(
              _FakePayPeriod_0(
                this,
                Invocation.method(#updatePayPeriod, [payPeriodId, request]),
              ),
            ),
          )
          as _i5.Future<_i2.PayPeriod>);

  @override
  _i5.Future<List<_i2.PayPeriod>> generatePayPeriods({
    required String? frequency,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generatePayPeriods, [], {
              #frequency: frequency,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<List<_i2.PayPeriod>>.value(
              <_i2.PayPeriod>[],
            ),
          )
          as _i5.Future<List<_i2.PayPeriod>>);

  @override
  _i5.Future<void> deletePayPeriod(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePayPeriod, [payPeriodId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.PayPeriod> activatePayPeriod(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#activatePayPeriod, [payPeriodId]),
            returnValue: _i5.Future<_i2.PayPeriod>.value(
              _FakePayPeriod_0(
                this,
                Invocation.method(#activatePayPeriod, [payPeriodId]),
              ),
            ),
          )
          as _i5.Future<_i2.PayPeriod>);

  @override
  _i5.Future<_i2.PayPeriod> processPayPeriod(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#processPayPeriod, [payPeriodId]),
            returnValue: _i5.Future<_i2.PayPeriod>.value(
              _FakePayPeriod_0(
                this,
                Invocation.method(#processPayPeriod, [payPeriodId]),
              ),
            ),
          )
          as _i5.Future<_i2.PayPeriod>);

  @override
  _i5.Future<_i2.PayPeriod> completePayPeriod(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#completePayPeriod, [payPeriodId]),
            returnValue: _i5.Future<_i2.PayPeriod>.value(
              _FakePayPeriod_0(
                this,
                Invocation.method(#completePayPeriod, [payPeriodId]),
              ),
            ),
          )
          as _i5.Future<_i2.PayPeriod>);

  @override
  _i5.Future<_i2.PayPeriod> closePayPeriod(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#closePayPeriod, [payPeriodId]),
            returnValue: _i5.Future<_i2.PayPeriod>.value(
              _FakePayPeriod_0(
                this,
                Invocation.method(#closePayPeriod, [payPeriodId]),
              ),
            ),
          )
          as _i5.Future<_i2.PayPeriod>);

  @override
  _i5.Future<_i2.PayPeriod> reopenPayPeriod(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#reopenPayPeriod, [payPeriodId]),
            returnValue: _i5.Future<_i2.PayPeriod>.value(
              _FakePayPeriod_0(
                this,
                Invocation.method(#reopenPayPeriod, [payPeriodId]),
              ),
            ),
          )
          as _i5.Future<_i2.PayPeriod>);

  @override
  _i5.Future<void> updatePayPeriodStatus(String? payPeriodId, String? action) =>
      (super.noSuchMethod(
            Invocation.method(#updatePayPeriodStatus, [payPeriodId, action]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> generatePayslips(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#generatePayslips, [payPeriodId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [PayrollRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPayrollRepository extends _i1.Mock implements _i6.PayrollRepository {
  MockPayrollRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i4.PayrollCalculation>> calculatePayroll(
    List<String>? workerIds, {
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #calculatePayroll,
              [workerIds],
              {#startDate: startDate, #endDate: endDate},
            ),
            returnValue: _i5.Future<List<_i4.PayrollCalculation>>.value(
              <_i4.PayrollCalculation>[],
            ),
          )
          as _i5.Future<List<_i4.PayrollCalculation>>);

  @override
  _i5.Future<_i4.PayrollProcessResponse> processPayroll(
    List<String>? workerIds,
    String? payPeriodId, {
    bool? skipPayout = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processPayroll,
              [workerIds, payPeriodId],
              {#skipPayout: skipPayout},
            ),
            returnValue: _i5.Future<_i4.PayrollProcessResponse>.value(
              _FakePayrollProcessResponse_2(
                this,
                Invocation.method(
                  #processPayroll,
                  [workerIds, payPeriodId],
                  {#skipPayout: skipPayout},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.PayrollProcessResponse>);

  @override
  _i5.Future<_i4.FundVerificationResult> verifyFunds(
    String? payPeriodId, {
    List<String>? workerIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #verifyFunds,
              [payPeriodId],
              {#workerIds: workerIds},
            ),
            returnValue: _i5.Future<_i4.FundVerificationResult>.value(
              _FakeFundVerificationResult_3(
                this,
                Invocation.method(
                  #verifyFunds,
                  [payPeriodId],
                  {#workerIds: workerIds},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.FundVerificationResult>);

  @override
  _i5.Future<_i4.JobStatusResult> getJobStatus(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#getJobStatus, [jobId]),
            returnValue: _i5.Future<_i4.JobStatusResult>.value(
              _FakeJobStatusResult_4(
                this,
                Invocation.method(#getJobStatus, [jobId]),
              ),
            ),
          )
          as _i5.Future<_i4.JobStatusResult>);

  @override
  _i5.Future<Map<String, dynamic>> devTopup(double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#devTopup, [amount]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i4.PayrollCalculation>> saveDraftPayroll(
    String? payPeriodId,
    List<Map<String, dynamic>>? items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraftPayroll, [payPeriodId, items]),
            returnValue: _i5.Future<List<_i4.PayrollCalculation>>.value(
              <_i4.PayrollCalculation>[],
            ),
          )
          as _i5.Future<List<_i4.PayrollCalculation>>);

  @override
  _i5.Future<List<_i4.PayrollCalculation>> getDraftPayroll(
    String? payPeriodId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDraftPayroll, [payPeriodId]),
            returnValue: _i5.Future<List<_i4.PayrollCalculation>>.value(
              <_i4.PayrollCalculation>[],
            ),
          )
          as _i5.Future<List<_i4.PayrollCalculation>>);

  @override
  _i5.Future<List<_i4.PayrollCalculation>> getPeriodRecords(
    String? payPeriodId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPeriodRecords, [payPeriodId]),
            returnValue: _i5.Future<List<_i4.PayrollCalculation>>.value(
              <_i4.PayrollCalculation>[],
            ),
          )
          as _i5.Future<List<_i4.PayrollCalculation>>);

  @override
  _i5.Future<_i4.PayrollCalculation> updatePayrollItem(
    String? payrollRecordId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePayrollItem, [payrollRecordId, updates]),
            returnValue: _i5.Future<_i4.PayrollCalculation>.value(
              _FakePayrollCalculation_5(
                this,
                Invocation.method(#updatePayrollItem, [
                  payrollRecordId,
                  updates,
                ]),
              ),
            ),
          )
          as _i5.Future<_i4.PayrollCalculation>);

  @override
  _i5.Future<List<_i4.PayrollCalculation>> recalculatePayroll(
    String? payPeriodId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recalculatePayroll, [payPeriodId]),
            returnValue: _i5.Future<List<_i4.PayrollCalculation>>.value(
              <_i4.PayrollCalculation>[],
            ),
          )
          as _i5.Future<List<_i4.PayrollCalculation>>);

  @override
  _i5.Future<void> deletePayrollItem(String? payrollRecordId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePayrollItem, [payrollRecordId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> finalizePayroll(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#finalizePayroll, [payPeriodId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<int>> downloadPayslip(String? payrollRecordId) =>
      (super.noSuchMethod(
            Invocation.method(#downloadPayslip, [payrollRecordId]),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<_i4.PayslipPreview> getPayslipPreview(String? payrollRecordId) =>
      (super.noSuchMethod(
            Invocation.method(#getPayslipPreview, [payrollRecordId]),
            returnValue: _i5.Future<_i4.PayslipPreview>.value(
              _FakePayslipPreview_6(
                this,
                Invocation.method(#getPayslipPreview, [payrollRecordId]),
              ),
            ),
          )
          as _i5.Future<_i4.PayslipPreview>);

  @override
  _i5.Future<_i4.PayrollSummary> getPayrollSummary(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#getPayrollSummary, [payPeriodId]),
            returnValue: _i5.Future<_i4.PayrollSummary>.value(
              _FakePayrollSummary_7(
                this,
                Invocation.method(#getPayrollSummary, [payPeriodId]),
              ),
            ),
          )
          as _i5.Future<_i4.PayrollSummary>);

  @override
  _i5.Future<List<_i6.WorkerPaymentHistoryItem>> getWorkerHistory(
    String? workerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkerHistory, [workerId]),
            returnValue: _i5.Future<List<_i6.WorkerPaymentHistoryItem>>.value(
              <_i6.WorkerPaymentHistoryItem>[],
            ),
          )
          as _i5.Future<List<_i6.WorkerPaymentHistoryItem>>);

  @override
  _i5.Future<List<_i4.WorkerPaymentStatus>> getPaymentStatus(
    String? payPeriodId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentStatus, [payPeriodId]),
            returnValue: _i5.Future<List<_i4.WorkerPaymentStatus>>.value(
              <_i4.WorkerPaymentStatus>[],
            ),
          )
          as _i5.Future<List<_i4.WorkerPaymentStatus>>);
}
