// Mocks generated by Mockito 5.4.6 from annotations
// in mobile/test/integrations/intasend_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i3;
import 'package:mobile/core/network/api_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlutterSecureStorage_1 extends _i1.SmartFake
    implements _i3.FlutterSecureStorage {
  _FakeFlutterSecureStorage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthEndpoints_2 extends _i1.SmartFake implements _i4.AuthEndpoints {
  _FakeAuthEndpoints_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayrollEndpoints_3 extends _i1.SmartFake
    implements _i4.PayrollEndpoints {
  _FakePayrollEndpoints_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayPeriodEndpoints_4 extends _i1.SmartFake
    implements _i4.PayPeriodEndpoints {
  _FakePayPeriodEndpoints_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaxEndpoints_5 extends _i1.SmartFake implements _i4.TaxEndpoints {
  _FakeTaxEndpoints_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentEndpoints_6 extends _i1.SmartFake
    implements _i4.PaymentEndpoints {
  _FakePaymentEndpoints_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubscriptionEndpoints_7 extends _i1.SmartFake
    implements _i4.SubscriptionEndpoints {
  _FakeSubscriptionEndpoints_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccountingEndpoints_8 extends _i1.SmartFake
    implements _i4.AccountingEndpoints {
  _FakeAccountingEndpoints_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLeaveEndpoints_9 extends _i1.SmartFake
    implements _i4.LeaveEndpoints {
  _FakeLeaveEndpoints_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkerEndpoints_10 extends _i1.SmartFake
    implements _i4.WorkerEndpoints {
  _FakeWorkerEndpoints_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReportEndpoints_11 extends _i1.SmartFake
    implements _i4.ReportEndpoints {
  _FakeReportEndpoints_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmployeePortalEndpoints_12 extends _i1.SmartFake
    implements _i4.EmployeePortalEndpoints {
  _FakeEmployeePortalEndpoints_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTimeTrackingEndpoints_13 extends _i1.SmartFake
    implements _i4.TimeTrackingEndpoints {
  _FakeTimeTrackingEndpoints_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePropertyEndpoints_14 extends _i1.SmartFake
    implements _i4.PropertyEndpoints {
  _FakePropertyEndpoints_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkersConvertEndpoints_15 extends _i1.SmartFake
    implements _i4.WorkersConvertEndpoints {
  _FakeWorkersConvertEndpoints_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadEndpoints_16 extends _i1.SmartFake
    implements _i4.UploadEndpoints {
  _FakeUploadEndpoints_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGovEndpoints_17 extends _i1.SmartFake implements _i4.GovEndpoints {
  _FakeGovEndpoints_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_18<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeException_19 extends _i1.SmartFake implements Exception {
  _FakeException_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i3.FlutterSecureStorage get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeFlutterSecureStorage_1(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i3.FlutterSecureStorage);

  @override
  _i4.AuthEndpoints get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuthEndpoints_2(this, Invocation.getter(#auth)),
          )
          as _i4.AuthEndpoints);

  @override
  _i4.PayrollEndpoints get payroll =>
      (super.noSuchMethod(
            Invocation.getter(#payroll),
            returnValue: _FakePayrollEndpoints_3(
              this,
              Invocation.getter(#payroll),
            ),
          )
          as _i4.PayrollEndpoints);

  @override
  _i4.PayPeriodEndpoints get payPeriods =>
      (super.noSuchMethod(
            Invocation.getter(#payPeriods),
            returnValue: _FakePayPeriodEndpoints_4(
              this,
              Invocation.getter(#payPeriods),
            ),
          )
          as _i4.PayPeriodEndpoints);

  @override
  _i4.TaxEndpoints get taxes =>
      (super.noSuchMethod(
            Invocation.getter(#taxes),
            returnValue: _FakeTaxEndpoints_5(this, Invocation.getter(#taxes)),
          )
          as _i4.TaxEndpoints);

  @override
  _i4.PaymentEndpoints get payments =>
      (super.noSuchMethod(
            Invocation.getter(#payments),
            returnValue: _FakePaymentEndpoints_6(
              this,
              Invocation.getter(#payments),
            ),
          )
          as _i4.PaymentEndpoints);

  @override
  _i4.SubscriptionEndpoints get subscriptions =>
      (super.noSuchMethod(
            Invocation.getter(#subscriptions),
            returnValue: _FakeSubscriptionEndpoints_7(
              this,
              Invocation.getter(#subscriptions),
            ),
          )
          as _i4.SubscriptionEndpoints);

  @override
  _i4.AccountingEndpoints get accounting =>
      (super.noSuchMethod(
            Invocation.getter(#accounting),
            returnValue: _FakeAccountingEndpoints_8(
              this,
              Invocation.getter(#accounting),
            ),
          )
          as _i4.AccountingEndpoints);

  @override
  _i4.LeaveEndpoints get leave =>
      (super.noSuchMethod(
            Invocation.getter(#leave),
            returnValue: _FakeLeaveEndpoints_9(this, Invocation.getter(#leave)),
          )
          as _i4.LeaveEndpoints);

  @override
  _i4.WorkerEndpoints get workers =>
      (super.noSuchMethod(
            Invocation.getter(#workers),
            returnValue: _FakeWorkerEndpoints_10(
              this,
              Invocation.getter(#workers),
            ),
          )
          as _i4.WorkerEndpoints);

  @override
  _i4.ReportEndpoints get reports =>
      (super.noSuchMethod(
            Invocation.getter(#reports),
            returnValue: _FakeReportEndpoints_11(
              this,
              Invocation.getter(#reports),
            ),
          )
          as _i4.ReportEndpoints);

  @override
  _i4.EmployeePortalEndpoints get employeePortal =>
      (super.noSuchMethod(
            Invocation.getter(#employeePortal),
            returnValue: _FakeEmployeePortalEndpoints_12(
              this,
              Invocation.getter(#employeePortal),
            ),
          )
          as _i4.EmployeePortalEndpoints);

  @override
  _i4.TimeTrackingEndpoints get timeTracking =>
      (super.noSuchMethod(
            Invocation.getter(#timeTracking),
            returnValue: _FakeTimeTrackingEndpoints_13(
              this,
              Invocation.getter(#timeTracking),
            ),
          )
          as _i4.TimeTrackingEndpoints);

  @override
  _i4.PropertyEndpoints get properties =>
      (super.noSuchMethod(
            Invocation.getter(#properties),
            returnValue: _FakePropertyEndpoints_14(
              this,
              Invocation.getter(#properties),
            ),
          )
          as _i4.PropertyEndpoints);

  @override
  _i4.WorkersConvertEndpoints get workersConvert =>
      (super.noSuchMethod(
            Invocation.getter(#workersConvert),
            returnValue: _FakeWorkersConvertEndpoints_15(
              this,
              Invocation.getter(#workersConvert),
            ),
          )
          as _i4.WorkersConvertEndpoints);

  @override
  _i4.UploadEndpoints get uploads =>
      (super.noSuchMethod(
            Invocation.getter(#uploads),
            returnValue: _FakeUploadEndpoints_16(
              this,
              Invocation.getter(#uploads),
            ),
          )
          as _i4.UploadEndpoints);

  @override
  _i4.GovEndpoints get gov =>
      (super.noSuchMethod(
            Invocation.getter(#gov),
            returnValue: _FakeGovEndpoints_17(this, Invocation.getter(#gov)),
          )
          as _i4.GovEndpoints);

  @override
  set auth(_i4.AuthEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#auth, value),
    returnValueForMissingStub: null,
  );

  @override
  set payroll(_i4.PayrollEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#payroll, value),
    returnValueForMissingStub: null,
  );

  @override
  set payPeriods(_i4.PayPeriodEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#payPeriods, value),
    returnValueForMissingStub: null,
  );

  @override
  set taxes(_i4.TaxEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#taxes, value),
    returnValueForMissingStub: null,
  );

  @override
  set payments(_i4.PaymentEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#payments, value),
    returnValueForMissingStub: null,
  );

  @override
  set subscriptions(_i4.SubscriptionEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#subscriptions, value),
    returnValueForMissingStub: null,
  );

  @override
  set accounting(_i4.AccountingEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#accounting, value),
    returnValueForMissingStub: null,
  );

  @override
  set leave(_i4.LeaveEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#leave, value),
    returnValueForMissingStub: null,
  );

  @override
  set workers(_i4.WorkerEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#workers, value),
    returnValueForMissingStub: null,
  );

  @override
  set reports(_i4.ReportEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#reports, value),
    returnValueForMissingStub: null,
  );

  @override
  set employeePortal(_i4.EmployeePortalEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#employeePortal, value),
    returnValueForMissingStub: null,
  );

  @override
  set timeTracking(_i4.TimeTrackingEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#timeTracking, value),
    returnValueForMissingStub: null,
  );

  @override
  set properties(_i4.PropertyEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#properties, value),
    returnValueForMissingStub: null,
  );

  @override
  set workersConvert(_i4.WorkersConvertEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#workersConvert, value),
    returnValueForMissingStub: null,
  );

  @override
  set uploads(_i4.UploadEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#uploads, value),
    returnValueForMissingStub: null,
  );

  @override
  set gov(_i4.GovEndpoints? value) => super.noSuchMethod(
    Invocation.setter(#gov, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParams,
    _i2.Options? options,
    bool? noCache = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParams: queryParams, #options: options, #noCache: noCache},
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #queryParams: queryParams,
                    #options: options,
                    #noCache: noCache,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> post(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParams,
    _i2.Options? options,
    bool? noCache = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParams: queryParams,
                #options: options,
                #noCache: noCache,
              },
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParams: queryParams,
                    #options: options,
                    #noCache: noCache,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> patch(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParams,
    _i2.Options? options,
    bool? noCache = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParams: queryParams,
                #options: options,
                #noCache: noCache,
              },
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParams: queryParams,
                    #options: options,
                    #noCache: noCache,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> delete(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParams,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {#data: data, #queryParams: queryParams, #options: options},
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {#data: data, #queryParams: queryParams, #options: options},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  String getErrorMessage(dynamic error) =>
      (super.noSuchMethod(
            Invocation.method(#getErrorMessage, [error]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getErrorMessage, [error]),
            ),
          )
          as String);

  @override
  Exception handleError(dynamic error) =>
      (super.noSuchMethod(
            Invocation.method(#handleError, [error]),
            returnValue: _FakeException_19(
              this,
              Invocation.method(#handleError, [error]),
            ),
          )
          as Exception);

  @override
  _i5.Future<_i2.Response<dynamic>> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> register(
    String? email,
    String? password, {
    String? firstName,
    String? lastName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #register,
              [email, password],
              {#firstName: firstName, #lastName: lastName},
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(
                  #register,
                  [email, password],
                  {#firstName: firstName, #lastName: lastName},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getWorkers() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkers, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getWorkers, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> createWorker(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createWorker, [data]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#createWorker, [data]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> updateWorker(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorker, [id, data]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#updateWorker, [id, data]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> deleteWorker(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorker, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#deleteWorker, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getPayPeriods() =>
      (super.noSuchMethod(
            Invocation.method(#getPayPeriods, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getPayPeriods, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getPayPeriodById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPayPeriodById, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getPayPeriodById, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> createPayPeriod(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPayPeriod, [data]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#createPayPeriod, [data]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> updatePayPeriod(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePayPeriod, [id, data]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#updatePayPeriod, [id, data]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> deletePayPeriod(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePayPeriod, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#deletePayPeriod, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> activatePayPeriod(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#activatePayPeriod, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#activatePayPeriod, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> processPayPeriod(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#processPayPeriod, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#processPayPeriod, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> completePayPeriod(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#completePayPeriod, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#completePayPeriod, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> closePayPeriod(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#closePayPeriod, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#closePayPeriod, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getPayPeriodStatistics(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPayPeriodStatistics, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getPayPeriodStatistics, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getCurrentPayPeriod() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPayPeriod, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getCurrentPayPeriod, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> saveDraftPayroll(
    String? payPeriodId,
    List<Map<String, dynamic>>? items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraftPayroll, [payPeriodId, items]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#saveDraftPayroll, [payPeriodId, items]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> updatePayrollItem(
    String? id,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePayrollItem, [id, updates]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#updatePayrollItem, [id, updates]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getDraftPayroll(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#getDraftPayroll, [payPeriodId]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getDraftPayroll, [payPeriodId]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> finalizePayroll(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#finalizePayroll, [payPeriodId]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#finalizePayroll, [payPeriodId]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<List<int>> downloadPayslip(String? payrollRecordId) =>
      (super.noSuchMethod(
            Invocation.method(#downloadPayslip, [payrollRecordId]),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<_i2.Response<dynamic>> calculateTax(double? grossSalary) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTax, [grossSalary]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#calculateTax, [grossSalary]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getTaxSubmissions() =>
      (super.noSuchMethod(
            Invocation.method(#getTaxSubmissions, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getTaxSubmissions, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> markTaxAsFiled(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markTaxAsFiled, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#markTaxAsFiled, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getCurrentTaxTable() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentTaxTable, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getCurrentTaxTable, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getComplianceStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getComplianceStatus, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getComplianceStatus, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getTaxDeadlines() =>
      (super.noSuchMethod(
            Invocation.method(#getTaxDeadlines, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getTaxDeadlines, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> exportPayrollToCSV(String? payPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#exportPayrollToCSV, [payPeriodId]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#exportPayrollToCSV, [payPeriodId]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getRecentActivities({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentActivities, [], {#limit: limit}),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getRecentActivities, [], {#limit: limit}),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getAccountMappings() =>
      (super.noSuchMethod(
            Invocation.method(#getAccountMappings, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getAccountMappings, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> saveAccountMappings(
    Map<String, dynamic>? mappings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccountMappings, [mappings]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#saveAccountMappings, [mappings]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getLeaveRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getLeaveRequests, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getLeaveRequests, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getWorkerLeaveRequests(String? workerId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkerLeaveRequests, [workerId]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getWorkerLeaveRequests, [workerId]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> createLeaveRequest(
    String? workerId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createLeaveRequest, [workerId, data]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#createLeaveRequest, [workerId, data]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> updateLeaveRequest(
    String? leaveRequestId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLeaveRequest, [leaveRequestId, data]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#updateLeaveRequest, [leaveRequestId, data]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> deleteLeaveRequest(
    String? leaveRequestId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLeaveRequest, [leaveRequestId]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#deleteLeaveRequest, [leaveRequestId]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> approveLeaveRequest(
    String? leaveRequestId,
    bool? approved, {
    String? comments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #approveLeaveRequest,
              [leaveRequestId, approved],
              {#comments: comments},
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(
                  #approveLeaveRequest,
                  [leaveRequestId, approved],
                  {#comments: comments},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getLeaveBalance(String? workerId) =>
      (super.noSuchMethod(
            Invocation.method(#getLeaveBalance, [workerId]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getLeaveBalance, [workerId]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getPayrollRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getPayrollRecords, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getPayrollRecords, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> updatePayrollStatus(
    String? id,
    String? status, {
    String? paymentDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updatePayrollStatus,
              [id, status],
              {#paymentDate: paymentDate},
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(
                  #updatePayrollStatus,
                  [id, status],
                  {#paymentDate: paymentDate},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> deletePayrollRecord(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePayrollRecord, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#deletePayrollRecord, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getTransactions, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getTransactionById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionById, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getTransactionById, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getPaymentDashboard() =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentDashboard, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getPaymentDashboard, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getPaymentMethods() =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentMethods, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getPaymentMethods, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getTaxPaymentSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getTaxPaymentSummary, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getTaxPaymentSummary, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> initiateMpesaTopup(
    String? phoneNumber,
    double? amount, {
    String? accountReference,
    String? transactionDesc,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initiateMpesaTopup,
              [phoneNumber, amount],
              {
                #accountReference: accountReference,
                #transactionDesc: transactionDesc,
              },
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(
                  #initiateMpesaTopup,
                  [phoneNumber, amount],
                  {
                    #accountReference: accountReference,
                    #transactionDesc: transactionDesc,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> recordTaxPayment({
    required String? taxType,
    required double? amount,
    required String? reference,
    String? paymentDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordTaxPayment, [], {
              #taxType: taxType,
              #amount: amount,
              #reference: reference,
              #paymentDate: paymentDate,
            }),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#recordTaxPayment, [], {
                  #taxType: taxType,
                  #amount: amount,
                  #reference: reference,
                  #paymentDate: paymentDate,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getSubscriptionPlans() =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionPlans, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getSubscriptionPlans, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getUserSubscription() =>
      (super.noSuchMethod(
            Invocation.method(#getUserSubscription, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getUserSubscription, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getSubscriptionPaymentHistory({
    int? page,
    int? limit,
    String? status,
    String? startDate,
    String? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionPaymentHistory, [], {
              #page: page,
              #limit: limit,
              #status: status,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getSubscriptionPaymentHistory, [], {
                  #page: page,
                  #limit: limit,
                  #status: status,
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getCountries() =>
      (super.noSuchMethod(
            Invocation.method(#getCountries, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getCountries, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> markTaxSubmissionAsFiled(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markTaxSubmissionAsFiled, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#markTaxSubmissionAsFiled, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> generateTaxSubmission(
    String? payPeriodId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateTaxSubmission, [payPeriodId]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#generateTaxSubmission, [payPeriodId]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getMonthlyTaxSummary(
    int? year,
    int? month,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlyTaxSummary, [year, month]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getMonthlyTaxSummary, [year, month]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> recordTaxPaymentTax(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#recordTaxPaymentTax, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#recordTaxPaymentTax, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getTaxPaymentHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getTaxPaymentHistory, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getTaxPaymentHistory, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getPendingTaxPayments() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingTaxPayments, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getPendingTaxPayments, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> updateTaxPaymentStatus(
    String? id,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaxPaymentStatus, [id, status]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#updateTaxPaymentStatus, [id, status]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getTaxPaymentInstructions() =>
      (super.noSuchMethod(
            Invocation.method(#getTaxPaymentInstructions, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getTaxPaymentInstructions, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> updateUserProfile(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [data]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#updateUserProfile, [data]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> uploadWorkerExcel(
    List<int>? bytes,
    String? filename,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadWorkerExcel, [bytes, filename]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<int>> downloadWorkerTemplate() =>
      (super.noSuchMethod(
            Invocation.method(#downloadWorkerTemplate, []),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);
}

/// A class which mocks [PaymentEndpoints].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentEndpoints extends _i1.Mock implements _i4.PaymentEndpoints {
  MockPaymentEndpoints() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response<dynamic>> getDashboard() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboard, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getDashboard, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getWalletBalance() =>
      (super.noSuchMethod(
            Invocation.method(#getWalletBalance, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getWalletBalance, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getMethods() =>
      (super.noSuchMethod(
            Invocation.method(#getMethods, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getMethods, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> initiateMpesaTopup(
    String? phoneNumber,
    double? amount, {
    String? accountReference,
    String? transactionDesc,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initiateMpesaTopup,
              [phoneNumber, amount],
              {
                #accountReference: accountReference,
                #transactionDesc: transactionDesc,
              },
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(
                  #initiateMpesaTopup,
                  [phoneNumber, amount],
                  {
                    #accountReference: accountReference,
                    #transactionDesc: transactionDesc,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> initiateStkPush(
    String? phoneNumber,
    double? amount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#initiateStkPush, [phoneNumber, amount]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#initiateStkPush, [phoneNumber, amount]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> sendB2C({
    required String? transactionId,
    required String? phoneNumber,
    required double? amount,
    required String? remarks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendB2C, [], {
              #transactionId: transactionId,
              #phoneNumber: phoneNumber,
              #amount: amount,
              #remarks: remarks,
            }),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#sendB2C, [], {
                  #transactionId: transactionId,
                  #phoneNumber: phoneNumber,
                  #amount: amount,
                  #remarks: remarks,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getTaxPaymentSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getTaxPaymentSummary, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getTaxPaymentSummary, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> recordTaxPayment({
    required String? taxType,
    required double? amount,
    required String? reference,
    String? paymentDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordTaxPayment, [], {
              #taxType: taxType,
              #amount: amount,
              #reference: reference,
              #paymentDate: paymentDate,
            }),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#recordTaxPayment, [], {
                  #taxType: taxType,
                  #amount: amount,
                  #reference: reference,
                  #paymentDate: paymentDate,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getTransactions, []),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getTransactionById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionById, [id]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getTransactionById, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);
}
