import { Injectable } from '@nestjs/common';

const PDFDocument = require('pdfkit');
import { PayrollRecord } from './entities/payroll-record.entity';

@Injectable()
export class PayslipService {
  async generatePayslip(record: PayrollRecord): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const buffers: Buffer[] = [];

      doc.on('data', (buffer: Buffer) => buffers.push(buffer));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', (err: any) => reject(err));

      // Header
      doc.fontSize(20).text('PAYSLIP', { align: 'center' }).moveDown();

      doc
        .fontSize(12)
        .text('PayKey Payroll Services', { align: 'center' })
        .moveDown();

      // Worker & Period Details
      doc
        .fontSize(10)
        .text(`Worker Name: ${record.worker.name}`)
        .text(`Pay Period: ${record.payPeriodId}`) // Ideally fetch PayPeriod name
        .text(`Date: ${new Date().toLocaleDateString()}`)
        .moveDown();

      // Earnings Section
      doc
        .fontSize(14)
        .text('Earnings', { underline: true })
        .fontSize(10)
        .moveDown(0.5);

      this.addCurrencyRow(doc, 'Gross Salary', Number(record.grossSalary));
      if (Number(record.bonuses) > 0) {
        this.addCurrencyRow(doc, 'Bonuses', Number(record.bonuses));
      }
      if (Number(record.otherEarnings) > 0) {
        this.addCurrencyRow(
          doc,
          'Other Earnings',
          Number(record.otherEarnings),
        );
      }

      const totalEarnings =
        Number(record.grossSalary) +
        Number(record.bonuses) +
        Number(record.otherEarnings);
      doc.moveDown(0.5);
      this.addCurrencyRow(doc, 'Total Earnings', totalEarnings, true);
      doc.moveDown();

      // Deductions Section
      doc
        .fontSize(14)
        .text('Deductions', { underline: true })
        .fontSize(10)
        .moveDown(0.5);

      this.addCurrencyRow(doc, 'PAYE (Tax)', Number(record.taxBreakdown.paye));
      this.addCurrencyRow(doc, 'NSSF', Number(record.taxBreakdown.nssf));
      this.addCurrencyRow(doc, 'NHIF', Number(record.taxBreakdown.nhif));
      this.addCurrencyRow(
        doc,
        'Housing Levy',
        Number(record.taxBreakdown.housingLevy),
      );

      if (Number(record.otherDeductions) > 0) {
        this.addCurrencyRow(
          doc,
          'Other Deductions',
          Number(record.otherDeductions),
        );
      }

      const totalDeductions =
        Number(record.taxBreakdown.totalDeductions) +
        Number(record.otherDeductions);
      doc.moveDown(0.5);
      this.addCurrencyRow(doc, 'Total Deductions', totalDeductions, true);
      doc.moveDown();

      // Net Pay
      doc
        .fontSize(16)
        .font('Helvetica-Bold')
        .text(`Net Pay: KES ${Number(record.netSalary).toFixed(2)}`, {
          align: 'right',
        });

      // Footer
      doc
        .moveDown(2)
        .fontSize(8)
        .font('Helvetica')
        .text('Generated by PayKey', { align: 'center', color: 'grey' });

      doc.end();
    });
  }

  private addCurrencyRow(
    doc: any,
    label: string,
    amount: number,
    isBold = false,
  ) {
    const y = doc.y;
    doc
      .font(isBold ? 'Helvetica-Bold' : 'Helvetica')
      .text(label, 50, y)
      .text(`KES ${amount.toFixed(2)}`, 300, y, { align: 'right' });
  }
}
